//! Dev tool: emit the **browser-engine conformance golden**.
//!
//! For a set of images it records the native feature buffer (`feature::extract`)
//! and the native `render_ascii` text (the authoritative render). The wasm engine
//! bindings (`mosaic-wasm`) are then proven to reproduce both: extract-in-wasm ==
//! extract-native (bit-identical `f32`, incl. `libm::atan2f` across native/wasm),
//! and the full browser pipeline (extract -> Facet -> compose) == this native
//! render. Options are `Options{cols, ..default}` — exactly the density+edge
//! configuration the `facet_ramp` Facet implements.
//!
//! Run: `cargo run -p tessera-ascii --example emit_render_golden`

use std::fs;
use std::path::Path;

use tessera_ascii::{
    Grid, ImageRef, Options, feature, render_ascii, render_dither, render_structural,
};

/// Deterministic xorshift PRNG (matches the engine's test PRNG) so the golden is
/// reproducible without `Math.random`/`Date`.
struct Rng(u64);
impl Rng {
    fn next_u32(&mut self) -> u32 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        (x >> 32) as u32
    }
    fn range(&mut self, lo: u32, hi: u32) -> u32 {
        lo + self.next_u32() % (hi - lo)
    }
}

struct Case {
    name: String,
    w: u32,
    h: u32,
    cols: u32,
    rgba: Vec<u8>,
}

const CELL_ASPECT: f32 = 2.0; // Options::default().cell_aspect

fn main() {
    let cases = build_cases();
    let mut json = String::new();
    json.push_str("{\n");
    json.push_str(
        "  \"note\": \"AUTO-GENERATED by `cargo run -p tessera-ascii --example emit_render_golden`. Do not edit by hand.\",\n",
    );
    json.push_str(&format!("  \"cellAspect\": {CELL_ASPECT},\n"));
    json.push_str("  \"cases\": [\n");

    for (ci, case) in cases.iter().enumerate() {
        let img = ImageRef::new(case.w, case.h, &case.rgba).expect("valid image");
        let opts = Options {
            cols: case.cols,
            ..Options::default()
        };
        let text = render_ascii(&img, &opts).expect("render");
        let structural_text =
            render_structural(&img, opts.cols, opts.cell_aspect).expect("render structural");
        let dither_text = render_dither(&img, opts.cols, opts.cell_aspect).expect("render dither");
        let grid = Grid::new(case.w, case.h, opts.cols, opts.cell_aspect);
        let feats = feature::extract(&img, &grid).expect("extract features");

        json.push_str("    {\n");
        json.push_str(&format!("      \"name\": {:?},\n", case.name));
        json.push_str(&format!("      \"width\": {},\n", case.w));
        json.push_str(&format!("      \"height\": {},\n", case.h));
        json.push_str(&format!("      \"cols\": {},\n", case.cols));
        json.push_str(&format!("      \"gridCols\": {},\n", feats.cols));
        json.push_str(&format!("      \"gridRows\": {},\n", feats.rows));
        json.push_str(&format!("      \"stride\": {},\n", feats.stride));
        json.push_str(&format!("      \"rgba\": [{}],\n", join_u8(&case.rgba)));
        json.push_str(&format!(
            "      \"features\": [{}],\n",
            join_f32(&feats.data)
        ));
        json.push_str(&format!("      \"text\": \"{}\",\n", json_escape(&text)));
        json.push_str(&format!(
            "      \"structuralText\": \"{}\",\n",
            json_escape(&structural_text)
        ));
        json.push_str(&format!(
            "      \"ditherText\": \"{}\"\n",
            json_escape(&dither_text)
        ));
        json.push_str(if ci + 1 == cases.len() {
            "    }\n"
        } else {
            "    },\n"
        });
    }
    json.push_str("  ]\n}\n");

    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../mosaic-wasm/test");
    fs::create_dir_all(&out_dir).expect("create test dir");
    fs::write(out_dir.join("render_golden.json"), &json).expect("write render_golden.json");

    println!(
        "emit_render_golden: wrote {} cases to {}",
        cases.len(),
        out_dir.display()
    );
}

fn build_cases() -> Vec<Case> {
    let mut cases = Vec::new();

    // Structured images that guarantee edge glyphs and mid-tones, including a
    // diagonal gradient that lands the gradient angle in the '/' and '\' bins.
    cases.push(Case {
        name: "vertical_edge_32x20".into(),
        w: 32,
        h: 20,
        cols: 16,
        rgba: grayscale(32, 20, |x, _| if x < 16 { 0 } else { 255 }),
    });
    cases.push(Case {
        name: "horizontal_edge_32x20".into(),
        w: 32,
        h: 20,
        cols: 16,
        rgba: grayscale(32, 20, |_, y| if y < 10 { 0 } else { 255 }),
    });
    cases.push(Case {
        name: "horizontal_gradient_48x16".into(),
        w: 48,
        h: 16,
        cols: 24,
        rgba: grayscale(48, 16, |x, _| ((x * 255) / 47) as u8),
    });
    cases.push(Case {
        name: "diagonal_gradient_40x40".into(),
        w: 40,
        h: 40,
        cols: 20,
        rgba: grayscale(40, 40, |x, y| (((x + y) * 255) / 78) as u8),
    });

    // Noisy images: the hard case (diagonal edges, every ramp bin exercised).
    let mut rng = Rng(0x0DDB_1A5E_5BAD_5EED);
    for i in 0..4 {
        let w = rng.range(8, 40);
        let h = rng.range(8, 30);
        let cols = rng.range(8, 32);
        let rgba: Vec<u8> = (0..(w * h * 4)).map(|_| rng.next_u32() as u8).collect();
        cases.push(Case {
            name: format!("noise_{i}_{w}x{h}_cols{cols}"),
            w,
            h,
            cols,
            rgba,
        });
    }

    cases
}

fn grayscale(w: u32, h: u32, f: impl Fn(u32, u32) -> u8) -> Vec<u8> {
    let mut buf = vec![0u8; w as usize * h as usize * 4];
    for y in 0..h {
        for x in 0..w {
            let v = f(x, y);
            let i = (y as usize * w as usize + x as usize) * 4;
            buf[i] = v;
            buf[i + 1] = v;
            buf[i + 2] = v;
            buf[i + 3] = 255;
        }
    }
    buf
}

fn join_u8(v: &[u8]) -> String {
    v.iter()
        .map(|x| x.to_string())
        .collect::<Vec<_>>()
        .join(",")
}

fn join_f32(v: &[f32]) -> String {
    v.iter()
        .map(|x| format!("{x}"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn json_escape(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            c if (c as u32) < 0x20 => o.push_str(&format!("\\u{:04x}", c as u32)),
            c => o.push(c),
        }
    }
    o
}
