//! Dev tool: emit the **ABI conformance golden** shared by the native and browser
//! Facet hosts.
//!
//! It runs the proven native [`Sandbox::run_map`] on the real bootstrap Facet
//! (`facet_ramp.wasm`) over hand-crafted feature buffers that exercise a wide
//! luminance sweep, clamping, the edge-magnitude threshold, every edge-direction
//! bin, and each stride (1/2/3). The resulting `(features -> tokens)` vectors are
//! written as JSON alongside a byte-copy of the exact Facet wasm they came from.
//! The TypeScript browser host (`packages/facet-abi`) replays these and must
//! reproduce every token — that is what makes "preview == render" (D9) a checked
//! property rather than a hope.
//!
//! Run: `cargo run -p mosaic-runtime --example emit_golden`

use std::fs;
use std::path::Path;

use mosaic_runtime::{Limits, Sandbox};

/// The canonical Facet wasm — the same fixture the native integration tests use.
const FACET_WASM: &[u8] = include_bytes!("../../tessera-ascii/tests/facet_ramp.wasm");

struct Case {
    name: &'static str,
    stride: usize,
    features: Vec<f32>,
}

fn main() {
    let sandbox = Sandbox::new().expect("build sandbox");
    let facet = sandbox.compile(FACET_WASM).expect("compile facet");

    let cases = build_cases();
    let mut json = String::new();
    json.push_str("{\n");
    json.push_str(
        "  \"note\": \"AUTO-GENERATED by `cargo run -p mosaic-runtime --example emit_golden`. Do not edit by hand.\",\n",
    );
    json.push_str("  \"facetWasm\": \"fixtures/facet_ramp.wasm\",\n");
    json.push_str("  \"cases\": [\n");
    for (ci, case) in cases.iter().enumerate() {
        assert!(case.stride > 0, "case {} has zero stride", case.name);
        assert_eq!(
            case.features.len() % case.stride,
            0,
            "case {} feature buffer is ragged",
            case.name
        );
        let ncells = case.features.len() / case.stride;
        let tokens = sandbox
            .run_map(
                &facet,
                Limits::default(),
                &case.features,
                ncells,
                case.stride,
            )
            .unwrap_or_else(|e| panic!("run_map failed for case {}: {e}", case.name));

        json.push_str("    {\n");
        json.push_str(&format!("      \"name\": {:?},\n", case.name));
        json.push_str(&format!("      \"stride\": {},\n", case.stride));
        json.push_str(&format!("      \"ncells\": {ncells},\n"));
        json.push_str(&format!(
            "      \"features\": [{}],\n",
            join_f32(&case.features)
        ));
        json.push_str(&format!("      \"tokens\": [{}]\n", join_u32(&tokens)));
        json.push_str(if ci + 1 == cases.len() {
            "    }\n"
        } else {
            "    },\n"
        });
    }
    json.push_str("  ]\n");
    json.push_str("}\n");

    // Write into packages/facet-abi/test so the TS package is self-contained and
    // its fixtures are provably the exact bytes this run measured.
    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packages/facet-abi/test");
    let fixtures = out_dir.join("fixtures");
    fs::create_dir_all(&fixtures).expect("create fixtures dir");
    fs::write(fixtures.join("facet_ramp.wasm"), FACET_WASM).expect("write wasm copy");
    fs::write(out_dir.join("golden.json"), &json).expect("write golden.json");

    println!(
        "emit_golden: wrote {} cases + facet_ramp.wasm to {}",
        cases.len(),
        out_dir.display()
    );
}

/// Feature buffers chosen to exercise the ramp Facet's whole decision surface:
/// the density ramp across its range, clamping past [0,1], the edge-magnitude
/// threshold from just-below to just-above, all four edge-direction bins, and
/// strides 1/2/3 (luma-only, luma+mag, luma+mag+dir).
fn build_cases() -> Vec<Case> {
    use core::f32::consts::PI;

    let mut cases = Vec::new();

    // 1. Density sweep, luma only.
    let sweep: Vec<f32> = (0..=20).map(|i| i as f32 / 20.0).collect();
    cases.push(Case {
        name: "ramp_sweep_stride1",
        stride: 1,
        features: sweep,
    });

    // 2. Clamping below 0 and above 1.
    cases.push(Case {
        name: "clamp_stride1",
        stride: 1,
        features: vec![-0.5, 0.0, 0.25, 0.5, 0.75, 1.0, 1.5],
    });

    // 3. luma + magnitude; straddle the edge threshold (0.6).
    cases.push(Case {
        name: "threshold_stride2",
        stride: 2,
        features: vec![
            0.2, 0.0, // density
            0.2, 0.59, // just below -> density
            0.2, 0.60, // == threshold, not '>' -> density
            0.2, 0.61, // just above -> edge
            0.8, 1.0, // strong edge
        ],
    });

    // 4. luma + magnitude + direction; sweep dir across all four edge bins with a
    //    magnitude above threshold, plus a couple of sub-threshold density cells.
    let mut dirs = Vec::new();
    for &d in &[
        -PI,
        -3.0 * PI / 4.0,
        -PI / 2.0,
        -PI / 4.0,
        0.0,
        PI / 4.0,
        PI / 2.0,
        3.0 * PI / 4.0,
        PI,
    ] {
        dirs.extend_from_slice(&[0.5, 1.0, d]); // strong edge
    }
    dirs.extend_from_slice(&[0.3, 0.1, 0.0]); // sub-threshold -> density
    dirs.extend_from_slice(&[0.9, 0.2, 1.23]); // sub-threshold -> density
    cases.push(Case {
        name: "edge_dirs_stride3",
        stride: 3,
        features: dirs,
    });

    // 5. Threshold boundary at full precision, stride 3.
    cases.push(Case {
        name: "threshold_boundary_stride3",
        stride: 3,
        features: vec![
            0.5, 0.6, 1.2, // == threshold -> density
            0.5, 0.600001, 1.2, // just above -> edge
        ],
    });

    cases
}

fn join_f32(v: &[f32]) -> String {
    v.iter()
        .map(|x| format!("{x}"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn join_u32(v: &[u32]) -> String {
    v.iter()
        .map(|x| x.to_string())
        .collect::<Vec<_>>()
        .join(", ")
}
