//! Emit the certificate golden shared by the native and browser conformance gates.
//!
//! Certifies real shipped Facets — `facet_ramp` (gather) and `facet_dither`
//! (propagation) — through the authoritative host and writes each [`Certificate`]
//! alongside the fixture path it attests. The browser verifier (`verifyCertificate` in
//! `@mosaic/facet-abi`) replays each certificate's probes and must reproduce every
//! outcome, extending "preview == render" (D9) to a certified Facet — a checked property,
//! not a hope, for an *arbitrary* Facet rather than only the hand-authored goldens.
//!
//! The Facet wasm fixtures are placed from source by `scripts/build-facets.sh`; this tool
//! only reads them. Its output (`cert_golden.json`) is regenerated and git-diff-gated by
//! `scripts/verify-fixtures.sh`.
//!
//! Run: `cargo run -p mosaic-certify --example emit_cert_golden`

use std::fs;
use std::path::PathBuf;

use mosaic_certify::{Certificate, CertifyOutcome, certify};
use mosaic_runtime::Sandbox;
use serde::Serialize;

// The exact fixtures the browser test loads, so each certificate's hash matches the bytes
// the verifier compiles.
const FACET_RAMP: &[u8] =
    include_bytes!("../../../packages/facet-abi/test/fixtures/facet_ramp.wasm");
const FACET_DITHER: &[u8] =
    include_bytes!("../../../packages/facet-abi/test/fixtures/facet_dither.wasm");

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct GoldenCase {
    /// Path (relative to the test directory) of the Facet wasm this certificate attests.
    facet_wasm: String,
    certificate: Certificate,
}

#[derive(Serialize)]
struct Golden {
    note: String,
    cases: Vec<GoldenCase>,
}

fn cert(sandbox: &Sandbox, bytes: &[u8], name: &str) -> Certificate {
    match certify(sandbox, bytes) {
        CertifyOutcome::Certified(cert) => cert,
        CertifyOutcome::Rejected(r) => panic!("{name} did not certify: {r}"),
    }
}

fn main() {
    let sandbox = Sandbox::new().expect("build sandbox");
    let golden = Golden {
        note: "AUTO-GENERATED by `cargo run -p mosaic-certify --example emit_cert_golden`. \
               Do not edit by hand. The browser verifier (verifyCertificate) replays each \
               certificate's probes and must reproduce every outcome, extending \
               'preview == render' to a certified Facet."
            .to_string(),
        cases: vec![
            GoldenCase {
                facet_wasm: "fixtures/facet_ramp.wasm".to_string(),
                certificate: cert(&sandbox, FACET_RAMP, "facet_ramp"),
            },
            GoldenCase {
                facet_wasm: "fixtures/facet_dither.wasm".to_string(),
                certificate: cert(&sandbox, FACET_DITHER, "facet_dither"),
            },
        ],
    };

    let mut json = serde_json::to_string_pretty(&golden).expect("serialize golden");
    json.push('\n');
    let out = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/facet-abi/test/cert_golden.json");
    fs::write(&out, json).expect("write cert_golden.json");

    println!(
        "emit_cert_golden: wrote {} certificates to {}",
        golden.cases.len(),
        out.display()
    );
}
