//! Emit the **DSL-program** certificate golden the browser verifier replays.
//!
//! Compiles real authored DSL Facets (`mosaic-dsl`) and certifies each through the shared
//! interpreter in the authoritative host ([`certify_program`]), writing each
//! [`ProgramCertificate`] alongside the exact bytecode it attests. The browser verifier
//! (`verifyProgramCertificate` in `@mosaic/facet-abi`) loads the interpreter fixture, replays
//! every probe, and must reproduce each outcome — extending "preview == render" (D9) to
//! authored DSL Facets, a checked property rather than a hope.
//!
//! The bytecode is emitted inline (a byte array) so the browser test is self-contained; it is
//! byte-identical to what the browser's own `compileDsl` produces from the same source (proven
//! separately), so this golden also pins that the two compilers agree.
//!
//! Run: `cargo run -p mosaic-certify --example emit_program_cert_golden`

use std::fs;
use std::path::PathBuf;

use mosaic_certify::{ProgramCertificate, ProgramCertifyOutcome, certify_program};
use mosaic_dsl::{Schema, compile};
use mosaic_runtime::Sandbox;
use serde::Serialize;

// The exact interpreter fixture the browser test loads, so the golden's tokens are produced by
// the same artifact the verifier runs.
const FACET_INTERP: &[u8] =
    include_bytes!("../../../packages/facet-abi/test/fixtures/facet_interp.wasm");

// The ASCII vocabulary (stride 3), matching the server's `ascii` engine.
const ASCII_SCHEMA: Schema = Schema {
    stride: 3,
    features: &[("luma", 0), ("grad_mag", 1), ("grad_dir", 2)],
    params: &[("threshold", 0.6)],
};

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct GoldenCase {
    /// The DSL source the bytecode was compiled from (documentation).
    source: String,
    /// The compiled bytecode the browser verifies, so the test needs no compiler.
    program: Vec<u8>,
    certificate: ProgramCertificate,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct Golden {
    note: String,
    /// The interpreter fixture (relative to the test dir) the browser loads and runs.
    facet_wasm: String,
    cases: Vec<GoldenCase>,
}

fn case(sandbox: &Sandbox, interp: &mosaic_runtime::Facet, src: &str) -> GoldenCase {
    let program = compile(src, &ASCII_SCHEMA).unwrap_or_else(|e| panic!("compile {src:?}: {e}"));
    let certificate = match certify_program(sandbox, interp, &program) {
        ProgramCertifyOutcome::Certified(c) => c,
        ProgramCertifyOutcome::Rejected(r) => panic!("{src:?} did not certify: {r}"),
    };
    GoldenCase {
        source: src.to_string(),
        program,
        certificate,
    }
}

fn main() {
    let sandbox = Sandbox::new().expect("build sandbox");
    let interp = sandbox
        .compile(FACET_INTERP)
        .expect("compile interp fixture");
    let golden = Golden {
        note: "AUTO-GENERATED by `cargo run -p mosaic-certify --example \
               emit_program_cert_golden`. Do not edit by hand. The browser verifier \
               (verifyProgramCertificate) replays each certificate's probes on the interpreter \
               fixture and must reproduce every outcome, extending 'preview == render' to \
               authored DSL Facets."
            .to_string(),
        facet_wasm: "fixtures/facet_interp.wasm".to_string(),
        cases: vec![
            // A density ramp.
            case(&sandbox, &interp, r#"ramp(luma, " .:-=+*#%@")"#),
            // A branchy Facet: strong edges pick a directional glyph, else density.
            case(
                &sandbox,
                &interp,
                r#"grad_mag > threshold ? glyph(clamp(grad_dir * 1.27 + 2.0, 0, 3), "-/|\\") : ramp(luma, " .:-=+*#%@")"#,
            ),
        ],
    };

    let mut json = serde_json::to_string_pretty(&golden).expect("serialize golden");
    json.push('\n');
    let out = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/facet-abi/test/program_cert_golden.json");
    fs::write(&out, json).expect("write program_cert_golden.json");

    println!(
        "emit_program_cert_golden: wrote {} program certificates to {}",
        golden.cases.len(),
        out.display()
    );
}
