//! Dev tool: emit the **spectral browser-engine conformance golden**.
//!
//! For a set of deterministic audio signals it records the native spectral feature
//! buffer (`feature::extract`) and the native `render_spectral` text (the authoritative
//! render). The wasm binding (`mosaic-wasm::extract_spectral_features`) is then proven
//! to reproduce the features bit-identically (incl. `libm::sinf`/`cosf`/`powf` across
//! native and wasm), and the full browser pipeline (extract → `facet-ramp` → compose) to
//! equal this native render — the preview == render guarantee for the audio engine.
//!
//! Every value here is deterministic across machines: signals use `libm::sinf` (never
//! std `f32::sin`, which is platform-dependent) and integer xorshift, so the golden
//! reproduces byte-for-byte and `scripts/verify-fixtures.sh` stays green on CI.
//!
//! Run: `cargo run -p tessera-spectral --example emit_spectral_golden`

use std::fs;
use std::path::Path;

use tessera_spectral::{SignalRef, SpectroGrid, feature, render_spectral};

const SAMPLE_RATE: u32 = 8000;
const BANDS: u32 = 16;
const WIN: u32 = 256;
const HOP: u32 = 128;
const FMIN: f32 = 120.0;
const FMAX: f32 = 3600.0;
const N: usize = 1024;
const TAU: f32 = core::f32::consts::TAU;

/// Deterministic xorshift PRNG (matches the engine's test PRNG) so the golden is
/// reproducible without `Math.random`/`Date`.
struct Rng(u64);
impl Rng {
    fn next_u32(&mut self) -> u32 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        (x >> 32) as u32
    }
    fn bipolar(&mut self) -> f32 {
        (self.next_u32() as f32 / u32::MAX as f32) * 2.0 - 1.0
    }
}

struct Case {
    name: String,
    samples: Vec<f32>,
}

fn main() {
    let grid = SpectroGrid::new(BANDS, WIN, HOP, FMIN, FMAX);
    let cases = build_cases(&grid);

    let mut json = String::new();
    json.push_str("{\n");
    json.push_str(
        "  \"note\": \"AUTO-GENERATED by `cargo run -p tessera-spectral --example emit_spectral_golden`. Do not edit by hand.\",\n",
    );
    json.push_str(&format!("  \"sampleRate\": {SAMPLE_RATE},\n"));
    json.push_str(&format!("  \"bands\": {BANDS},\n"));
    json.push_str(&format!("  \"win\": {WIN},\n"));
    json.push_str(&format!("  \"hop\": {HOP},\n"));
    json.push_str(&format!("  \"fmin\": {FMIN},\n"));
    json.push_str(&format!("  \"fmax\": {FMAX},\n"));
    json.push_str("  \"cases\": [\n");

    for (ci, case) in cases.iter().enumerate() {
        let sig = SignalRef::new(&case.samples, SAMPLE_RATE).expect("valid signal");
        let buf = feature::extract(&sig, &grid).expect("extract features");
        let text = render_spectral(&sig, &grid).expect("render");

        json.push_str("    {\n");
        json.push_str(&format!("      \"name\": {:?},\n", case.name));
        json.push_str(&format!(
            "      \"samples\": [{}],\n",
            join_f32(&case.samples)
        ));
        json.push_str(&format!("      \"gridCols\": {},\n", buf.cols));
        json.push_str(&format!("      \"gridRows\": {},\n", buf.rows));
        json.push_str(&format!("      \"stride\": {},\n", buf.stride));
        json.push_str(&format!("      \"features\": [{}],\n", join_f32(&buf.data)));
        json.push_str(&format!("      \"text\": \"{}\"\n", json_escape(&text)));
        json.push_str(if ci + 1 == cases.len() {
            "    }\n"
        } else {
            "    },\n"
        });
    }
    json.push_str("  ]\n}\n");

    let out_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../mosaic-wasm/test");
    fs::create_dir_all(&out_dir).expect("create test dir");
    fs::write(out_dir.join("spectral_golden.json"), &json).expect("write spectral_golden.json");

    println!(
        "emit_spectral_golden: wrote {} cases to {}",
        cases.len(),
        out_dir.display()
    );
}

fn build_cases(grid: &SpectroGrid) -> Vec<Case> {
    let mut cases = Vec::new();

    // A pure tone at band 8's center — a single clear horizontal band.
    let f8 = grid.band_center_hz(8);
    cases.push(Case {
        name: "tone_band8".into(),
        samples: (0..N)
            .map(|i| libm::sinf(TAU * f8 * i as f32 / SAMPLE_RATE as f32))
            .collect(),
    });

    // A three-tone chord (bands 3, 8, 12) — three bands lit at once.
    let f3 = grid.band_center_hz(3);
    let f12 = grid.band_center_hz(12);
    cases.push(Case {
        name: "chord_3_8_12".into(),
        samples: (0..N)
            .map(|i| {
                let t = i as f32 / SAMPLE_RATE as f32;
                (libm::sinf(TAU * f3 * t) + libm::sinf(TAU * f8 * t) + libm::sinf(TAU * f12 * t))
                    / 3.0
            })
            .collect(),
    });

    // Broadband xorshift noise — energy spread across all bands.
    let mut rng = Rng(0x5EED_0DDB_1A5E_1234);
    cases.push(Case {
        name: "noise".into(),
        samples: (0..N).map(|_| rng.bipolar()).collect(),
    });

    // A linear chirp fmin -> fmax via a phase accumulator — a rising diagonal.
    let mut phase = 0.0f32;
    let mut chirp = Vec::with_capacity(N);
    for i in 0..N {
        let f = FMIN + (FMAX - FMIN) * (i as f32 / N as f32);
        chirp.push(libm::sinf(phase));
        phase += TAU * f / SAMPLE_RATE as f32;
    }
    cases.push(Case {
        name: "chirp".into(),
        samples: chirp,
    });

    // A tone burst at band 10 in the middle third only — temporal localization.
    let f10 = grid.band_center_hz(10);
    cases.push(Case {
        name: "burst_band10".into(),
        samples: (0..N)
            .map(|i| {
                if (N / 3..2 * N / 3).contains(&i) {
                    libm::sinf(TAU * f10 * i as f32 / SAMPLE_RATE as f32)
                } else {
                    0.0
                }
            })
            .collect(),
    });

    cases
}

fn join_f32(v: &[f32]) -> String {
    v.iter()
        .map(|x| format!("{x}"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn json_escape(s: &str) -> String {
    let mut o = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '"' => o.push_str("\\\""),
            '\\' => o.push_str("\\\\"),
            '\n' => o.push_str("\\n"),
            c if (c as u32) < 0x20 => o.push_str(&format!("\\u{:04x}", c as u32)),
            c => o.push(c),
        }
    }
    o
}
